### ISSUE TITLE
Containers automatically start when I start docker

### ISSUE THREAD

**Issue by rossmc** [mage2click/m2c#10]
I tried out m2c a couple weeks ago, and I see it has great potential but I'm having a small issue with it.

Every-time I start Docker, the following containers also start:
<img width="1266" alt="Screenshot 2019-10-15 at 11 14 36" src="https://user-images.githubusercontent.com/2452991/66822905-0fe1a380-ef3d-11e9-964e-01f3d8c395b3.png">

These are containers, I created with `m2c init`.

This is inconvenient, as if I want to follow a different docker workflow.  I need to stop these containers every-time I start using docker.

How can I stop them from starting each time I start docker?

**Comment by shkoliar** [comment]
Hi @rossmc,

These are service containers which are used by `m2c` toolset and intended to be always active, they were created upon toolset installation. Check [Global system-wide services](https://github.com/mage2click/m2c#global-system-wide-services) section of the readme.

`m2c init` command only creates project-related containers that are supposed to be only active when you need to run a project, and they are not starting automatically like m2c service containers.

Currently, there is no switch to stop then starting, you can only remove toolset completely with `m2c global uninstall` command. 

I'm going to add a command to enable/disable the auto-starting of service containers in the closest release. 

Btw, for further reference, to update toolset, simply run `m2c global update`.
