### ISSUE TITLE
Magento Enterprise edition

### ISSUE THREAD

**Issue by freeyland** [mage2click/m2c#13]
Would be nice if also enterprise edition can be downloaded

**Comment by shkoliar** [comment]
Toolset uses Nexcess hosted Magento Open Source packages, unfortunately, Magento Commerce is not available there.

As an option, to use Magento Commerce with m2c toolset, you may try to download Magento Commerce sources manually from Magento website (special requires access is required) and initialize m2c project from existing sources.

**Comment by freeyland** [comment]
Maybe an other option is instead of downloading rom Nexus, that an install is done insedie the container with composer from official repo.

**Comment by freeyland** [comment]
For people interested:
if [[ -z ${E2C_CFG_MAGENTO_EDITION} ]]
then
          e2c_set_opt_version "Magento edition (CE or EE)" "${e2c_magento_editions[@]}"
fi

if [[ ${E2C_CFG_MAGENTO_EDITION} == "EE" ]]
then
            edition="project-enterprise-edition"
else
            edition="project-community-edition"
fi
       
if [[ -n ${E2C_CFG_MAGENTO_SRC} ]]
           m2c_msg "Composer install magento in temp folder................................  "
            m2c_loading
            m2c_composer create-project --repository=https://repo.magento.com magento/$edition=$E2C_CFG_MAGENTO ./temp >"$m2c_log" 2>&1
            m2c_result $?
            m2c_msg "Copy temp folder to /var/www/html/.....................................  "
            m2c_loading
            m2c_cli notty cp -r temp/. /var/www/html
            m2c_result $?
            m2c_msg "Remove temp folder ....................................................  "            
            m2c_loading
            m2c_cli notty rm -Rf temp >"$m2c_log" 2>&1
            m2c_result $?
            m2c_loading
            m2c_msg "Composer install hirak/prestissimo.....................................  "
            m2c_loading
            m2c_composer notty global require hirak/prestissimo >"$m2c_log" 2>&1
            m2c_result $?
            m2c_msg "Composer install cweagans/composer-patches.............................  "

            [[ "$e2c_os" == "darwin" ]] && e2c_pull --all
fi

**Comment by shkoliar** [comment]
I was thinking about adding an option like this, but it is easier to run `composer create-project` on the host to get Magento Commerce project files locally and then init mage2click project within that directory. `m2c init` will automatically detect Magento sources.
