### ISSUE TITLE
Bug when importing an existing db during init

### ISSUE THREAD

**Issue by freeyland** [mage2click/m2c#15]
On line 1329 in functions/m2C you are missing:
cd "$e2c_project_dir"

There is an issue when importing an existing db, the folder is in wrong location

**Comment by shkoliar** [comment]
What issue exactly? Toolset asks for a full path to plain SQL or gzipped database dump file.

**Comment by freeyland** [comment]
Instead  of skipping bin/magento install it is doing the install again instead of importing the db.
In m2c_local_project_up (called from m2c_local up) you are doing cd "$m2c_project_dir/.m2c/docker/" but not returning back to your $m2c_project_dir . As such the check on line 1336 (if [[ -f "$m2c_magento_db_import" ]]) is not working  as it does not find the sql file.

**Comment by shkoliar** [comment]
File-path is full? It must be a full path, not relative to project.

**Comment by freeyland** [comment]
I've tried full path but it did not work. I will check again.

**Comment by freeyland** [comment]
Ok, looks like an other problem. When hitting the back button on my mac for correcting the url, it does not work when I type /Users/frederick/Sites/roularta_abocopy/ci/config.sql.
WHen I do not make any mistake it is working. Very strange. Thanx  for the help

**Comment by shkoliar** [comment]
I'll review that part later. Maybe problem because of some invisible symbols.
