### ISSUE TITLE
Testing on Ubuntu

### ISSUE THREAD

**Issue by freeyland** [mage2click/m2c#17]
I am currently testing the install on Linux Ubuntu. However I am having issue on port 53 being used by the standard Linux DNS server. So  I get an error message saying that the port is already taken.
How did you make it work on Linux? 
Can I change the port of docker dnsmasq to 53 to eg port 54?  
I understand that DNSmasq is there so that all new created domains are available outside the docker environment?

**Comment by freeyland** [comment]
What is the reason you are forwarding port 53:53? There is no need for this I think as your Mac resolver (etc/resolver) is forwarding all .test traffic to 172.0.0.1
I've tested it without port fowarding 53:53 and it is also working.

**Comment by shkoliar** [comment]
Hey @freeyland,

We've not tested on Linux, so it would be great if you can test it! 

Regarding 53 port, it is default configuration from Dnsmasq docker image.

**Comment by freeyland** [comment]
Hey @shkoliar ,
The issue for Linux is that  port 53 is already taken by the default dns server from Ubuntu (or by standard dnsmasq installed on Ubuntu). I  am searching how the Mac /etc/resolver/test is going inside docker dnsmasq on port 53. 
I don't think is a good idea to stop standard Ubuntu DNS server as when the docker is not started you won't have any network.

**Comment by freeyland** [comment]
Following issues already found on Linux:

1. domain check not working
2. admin path url check not working
3. During init you do a push of scripts to container (e2c_push_exec). However this should not be done for Linux. The help message is displayed instead and the script is stopped.

I will continue testing....

**Comment by freeyland** [comment]
https://github.com/freeyland/e2c/tree/master
is working  with Linux. I still need to do some small tweaks. I will then make the changes on your repo  and make a merge request

**Comment by shkoliar** [comment]
> https://github.com/freeyland/e2c/tree/master

btw, @freeyland you have to keep the original copyright notice due to MIT License rules.

**Comment by freeyland** [comment]
Ok, will add it

**Comment by shkoliar** [comment]
@freeyland As I've noticed you are copying every our commit into your repo with adding your authorship. GitHub has `fork` and `pull requests` functionality which may allow you to have less "rewriting" work, of course if your goal is not "re-author" all this work.

It would be great if you can also give us feedback on Linux usage and create pull requests if you have improvements for Linux based systems.

**Comment by freeyland** [comment]
@shkoliar Today I am doing the latest tests on Ubuntu.
As promised, I will then merge all the changes I've made

**Comment by freeyland** [comment]
All working now on Ubunu. See latest merge request
