### ISSUE TITLE
Rebuilding the packages: something wrong

### ISSUE THREAD

**Issue by freeyland** [mage2click/m2c#18]
The command '/bin/sh -c apk update &&         apk add --no-cache             php7=${PHP_VERSION}             php7-bcmath=${PHP_VERSION}             php7-calendar=${PHP_VERSION}             php7-ctype=${PHP_VERSION}             php7-curl=${PHP_VERSION}             php7-dom=${PHP_VERSION}             php7-fpm=${PHP_VERSION}             php7-gd=${PHP_VERSION}             php7-gettext=${PHP_VERSION}             php7-iconv=${PHP_VERSION}             php7-intl=${PHP_VERSION}             php7-json=${PHP_VERSION}             php7-mbstring=${PHP_VERSION}             php7-mysqli=${PHP_VERSION}             php7-opcache=${PHP_VERSION}             php7-openssl=${PHP_VERSION}             php7-pdo_mysql=${PHP_VERSION}             php7-simplexml=${PHP_VERSION}             php7-soap=${PHP_VERSION}             php7-sockets=${PHP_VERSION}             php7-sodium=${PHP_VERSION}             php7-tokenizer=${PHP_VERSION}             php7-xml=${PHP_VERSION}             php7-xmlwriter=${PHP_VERSION}             php7-xsl=${PHP_VERSION}             php7-zip=${PHP_VERSION}             php7-pecl-amqp             php7-pecl-igbinary             php7-pecl-mcrypt             php7-pecl-redis             php7-pecl-ssh2             php7-pecl-xdebug             curl             gzip             lsof             supervisor &&                         sed -i -e 's/^;zend_extension/\zend_extension/g' /etc/php7/conf.d/xdebug.ini &&                         rm -rf /var/cache/apk/* &&         rm -rf /tmp/* &&                         addgroup -g 1000 -S app &&         adduser -u 1000 -S app -G app -h /var/www -s /bin/sh &&                         mkdir -p /var/www/html /var/www/.config /sock &&         touch /var/spool/cron/crontabs/app &&         chown -R app:app /var/www/html /var/www/.config             /etc/php7/conf.d /sock /var/log &&         chmod +x /usr/local/bin/docker-host /usr/local/bin/docker-php-entrypoint &&                         ln -sf /usr/sbin/php-fpm7 /usr/sbin/php-fpm &&         ln -sf /etc/init.d/php-fpm7 /etc/init.d/php-fpm' returned a non-zero code: 27
Error response from daemon: No such image: mage2click-m2c-php-fpm-7.3-xdebug-alpine:latest

**Comment by freeyland** [comment]
Found out that the packages are gone at Alpine

**Comment by freeyland** [comment]
As a result I cannot rebuild packages for Linux tests

**Comment by shkoliar** [comment]
What the reason for rebuilding docker images? These images are available at our docker hub organisation account. If you want to build your custom docker image, you can do it locally and tag it with your custom name.

`mage2click-m2c-php-fpm-7.3-xdebug-alpine:latest` is not correct image name and tag. 

If you want to pull image from docker hub, you need to use `mage2click/m2c:php-fpm-7.3-xdebug-alpine`.

**Comment by freeyland** [comment]
I want to rebuild the packages as they or not working for Ubuntu. 
The uid  (ud -i) from the container should match the one from your host.
This means in entrypoint we need to change uid and gid.

Also in php-fpm.conf your are missing:
user = app
group = app
As when rebuilding the images you will get a socket issue.
