### ISSUE TITLE
Custom port

### ISSUE THREAD

**Issue by webphpprojects** [mage2click/m2c#36]
I have a question, is there any way to use m2c tool with custom ports? Example: 81 instead of 80? If so how can I do it?

**Comment by shkoliar** [comment]
It is about ports that are exposed to the host machine? Currently, there is no way to change this, only possible by editing a docker-compose file (but this change will be lost after toolset update is executed).

**Comment by webphpprojects** [comment]
Ok, it would be a nice feature for this tool - regardless it's great tool. Then I have to change port for other projects :)
