### ISSUE TITLE
Custom database name

### ISSUE THREAD

**Issue by webphpprojects** [mage2click/m2c#39]
Hello,
I have a question related to database. Default m2c tool creates db with name magento. Is any way to change customize it and set other name of db? The problem is that I need to import dump of database which is quite big. It's hard to change  the name of database in large file (of course it's hard but possible), however maybe there is any way to access custom database?

**Comment by shkoliar** [comment]
Hello, @webphpprojects!

If you have m2c project up and have imported database with custom name, you can switch it by editing `.env` file in the project root. Check the `M2C_CFG_MYSQL_DATABASE` env variable.

**Comment by shkoliar** [comment]
The issue was closed accidentally. Anyway, we're checking on how to add a step for setting the database name during the import process.

**Comment by webphpprojects** [comment]
Thank you for both.
