### ISSUE TITLE
Conflict with already running dnsmasq process on port 53

### ISSUE THREAD

**Issue by grll** [mage2click/m2c#7]
When running the installation script I got the following error coming from a conflict on port 53:

Recreating m2c.test__dnsmasq ... error
 ERROR: for m2c.test__dnsmasq Cannot start service dnsmasq: driver failed programming external connectivity on endpoint m2c.test__dnsmasq (78cef79ac72e8a5fdd70983ab9e15fec6088c16feb231b17b45fe0899eb651a8): Error starting userland proxy: listen udp 0.0.0.0:53: bind: address already in use ERROR: for dnsmasq Cannot start service dnsmasq: driver failed programming external connectivity on endpoint m2c.test__dnsmasq (78cef79ac72e8a5fdd70983ab9e15fec6088c16feb231b17b45fe0899eb651a8): Error starting userland proxy: listen udp 0.0.0.0:53: bind: address already in use Encountered errors while bringing up the project.

**Comment by grll** [comment]
Solved by uninstalling dnsmasq and killing the process. Maybe worth adding check on port 53 on top of port 80 and 443 during installation process?

**Comment by shkoliar** [comment]
Hi @grll, that is a good catch!

I'm going to add a check also for that port.

**Comment by grll** [comment]
> Hi @grll, that is a good catch!
> 
> I'm going to add a check also for that port.

Great thanks! The toolset is really amazing by the way thanks a lot!
